channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - psycopg2
  - jupyter
  - ipywidgets
  - shapely 
  - itkwidgets 
  - k3d 
  - pykdtree 
  - pyembree
  - pip:
    - allensdk
    - caveclient>=4.4.0
    - meshparty>=1.12.0
    - vtkplotter
    - k3d
    - itkwidgets
